// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCst51kojGXWIcv3NkxIQx1JzYk0nUySA8',
    appId: '1:257476210398:web:8d85f1c41f74c9b6801c4f',
    messagingSenderId: '257476210398',
    projectId: 'lewas-4f9c9',
    authDomain: 'lewas-4f9c9.firebaseapp.com',
    storageBucket: 'lewas-4f9c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPFNsW7S6kgJQmQPd6eACM8JIWNA9ddk',
    appId: '1:257476210398:android:71b9eee0a0ed0ba2801c4f',
    messagingSenderId: '257476210398',
    projectId: 'lewas-4f9c9',
    storageBucket: 'lewas-4f9c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9y_nWMG6ZSOt1IWqh4m__uDFV9C5abfg',
    appId: '1:257476210398:ios:d954240d3b8bc769801c4f',
    messagingSenderId: '257476210398',
    projectId: 'lewas-4f9c9',
    storageBucket: 'lewas-4f9c9.appspot.com',
    iosClientId: '257476210398-3pi1eouphhlnvm2vos3evag73vsgvq3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnEnglish',
  );
}
